// Edit this file first. It contains every visible label, link, and project.
export const profile = {
  name: "Alexander Chen",
  role: "Digital designer and content strategist creating thoughtful, user-centered experiences.",
  bio: "Based in Toronto, with a background in Digital Enterprise Management from the University of Toronto.",
  email: "alexanderchen905@gmail.com",
  location: "Toronto",
  timeZone: "America/Toronto",
  updated: "09-08-2026",
  socials: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/alexanderchen-" },
    { label: "Resume", href: "/resume.pdf" },
  ],
};

export const loblawSubprojects = [
  {
    slug: "loblaw-careers-page",
    parentSlug: "loblaw-employer-brand",
    parentTitle: "Loblaw Companies Limited",
    title: "Loblaw Companies Limited Careers Page",
    description: "A reusable employer-brand system for Loblaw's careers experience, standardizing 23 banners across candidate touchpoints.",
    organization: "Loblaw Companies Limited",
    role: "Creative Specialist, Talent Strategy & Employer Branding",
    period: "2024 – 2026",
    impact: [
      "Designed and standardized 23 career-site banners in Figma, creating a reusable visual system across employer-brand touchpoints.",
      "Established a consistent visual direction for career content across pages and recruitment needs.",
      "Created a scalable foundation for future career-site content and campaign updates.",
    ],
    visual: "loblaw-careers",
    coverEyebrow: "Employer brand · Careers UX",
    coverTitle: "Careers Page",
    coverMetric: "23 standardized banners",
    aspect: "16 / 10",
  },
  {
    slug: "sharepoint-digital-toolkit",
    parentSlug: "loblaw-employer-brand",
    parentTitle: "Loblaw Companies Limited",
    title: "SharePoint Digital Toolkit",
    description: "A restructured global Talent Acquisition hub that centralizes reusable creative assets, templates, and workflows.",
    organization: "Loblaw Companies Limited",
    role: "Creative Specialist, Talent Strategy & Employer Branding",
    period: "2024 – 2026",
    impact: [
      "Used colleague feedback and UX data to restructure the global Talent Acquisition SharePoint hub.",
      "Centralized a toolkit containing 640+ templates, 32 banners, thousands of photos, and customizable LinkedIn assets.",
      "Organized high-volume resources into a clearer, more usable system for talent teams.",
    ],
    visual: "loblaw-toolkit",
    coverEyebrow: "UX · Information architecture",
    coverTitle: "Digital Toolkit",
    coverMetric: "640+ templates",
    aspect: "16 / 10",
  },
  {
    slug: "career-cafe-talent-talks",
    parentSlug: "loblaw-employer-brand",
    parentTitle: "Loblaw Companies Limited",
    title: "Career Cafe Talent Talk Series",
    description: "An internal career-growth initiative helping store colleagues explore pathways into franchise ownership, store management, and corporate roles.",
    organization: "Loblaw Companies Limited",
    role: "Creative Specialist, Talent Strategy & Employer Branding",
    period: "November 2024",
    impact: [
      "Supported an internal talent initiative designed to make career mobility and growth opportunities more visible to store colleagues.",
      "Helped shape and document a Talent Talk featuring pathways into franchise ownership, store management, and corporate roles.",
      "Supported the studio setup and behind-the-scenes content process for the live career conversation.",
    ],
    image: "/projects/work/loblaw/career-cafe/talent-talk-session.jpg",
    imageAlt: "Career Cafe Talent Talk session in the Loblaw studio",
    coverEyebrow: "Internal talent · Content",
    coverTitle: "Career Cafe",
    coverMetric: "Talent Talk Series",
    aspect: "4 / 3",
    mediaSections: [
      {
        eyebrow: "Behind the scenes · Setup and production",
        title: "Building the Talent Talk experience",
        description: "These photographs document the studio setup, filming process, and live conversation behind the Career Cafe Talent Talk Series.",
        layout: "portrait-pair",
        items: [
          {
            type: "image",
            src: "/projects/work/loblaw/career-cafe/talent-talk-setup.jpg",
            alt: "Alexander filming a Career Cafe Talent Talk during studio setup",
            caption: "Camera and studio setup for the Talent Talk",
            aspect: "3 / 4",
          },
          {
            type: "image",
            src: "/projects/work/loblaw/career-cafe/talent-talk-session.jpg",
            alt: "Career Cafe Talent Talk speakers and audience during the session",
            caption: "The Career Cafe Talent Talk in progress",
            aspect: "3 / 4",
          },
        ],
      },
    ],
  },
];

export const workProjects = [
  {
    slug: "tt-supermarket",
    title: "T&T Supermarket",
    description: "A localized, social-first Instagram and paid-media strategy that added 5,500+ followers and generated 5.22M impressions for a California launch.",
    organization: "T&T Supermarket Inc.",
    role: "Marketing Specialist, Media & Communications",
    period: "April 2026 – August 2026",
    impact: [
      "Developed and optimized a localized, social-first Instagram strategy, adding 5,500+ followers in three months and increasing followers by 2.08%, views by 202%, and engagements by 136% month over month.",
      "Coordinated paid Meta campaigns for new-store launches, refining audience targeting and testing creative variations to achieve a 1.93% click-through rate.",
      "Led the social rollout for T&T Supermarket's first California location, generating 5.22M impressions and helping build a grand-opening lineup of more than 500 customers.",
    ],
    visual: "tt",
    coverEyebrow: "Social strategy · Paid media",
    coverTitle: "California launch",
    coverMetric: "5.22M impressions",
    coverImage: "/projects/work/tt-supermarket/tt-logo-horizontal-green.png",
    coverImageAlt: "T&T Supermarket",
    coverImageStyle: "tt-logo",
    aspect: "1.85 / 1",
    mediaSections: [
      {
        eyebrow: "Paid social · Meta",
        title: "T&T Meta paid ads for San Jose store opening.",
        description: "Two social video ads developed for Meta paid media supporting T&T Supermarket's San Jose store opening.",
        layout: "portrait-square",
        items: [
          {
            type: "video",
            src: "/projects/work/tt-supermarket/san-jose-meta-ad-01.mp4",
            poster: "/projects/work/tt-supermarket/san-jose-meta-ad-01-poster.png",
            caption: "Meta paid ad · portrait",
            aspect: "9 / 16",
          },
          {
            type: "video",
            src: "/projects/work/tt-supermarket/san-jose-meta-ad-02.mp4",
            poster: "/projects/work/tt-supermarket/san-jose-meta-ad-02-poster.png",
            caption: "Meta paid ad · square",
            aspect: "1 / 1",
          },
        ],
      },
    ],
  },
  {
    slug: "loblaw-employer-brand",
    title: "Loblaw Companies Limited",
    description: "An employer-brand system spanning campaign creative, career-site banners, and a redesigned global talent-acquisition hub.",
    organization: "Loblaw Companies Limited",
    role: "Creative Specialist, Talent Strategy & Employer Branding",
    period: "2024 – 2026",
    impact: [
      "Launched a paid YouTube recruitment campaign for Asset Protection roles, generating 105,000+ impressions and 2,500+ clicks within two weeks.",
      "Designed and standardized 23 career-site banners in Figma, creating a reusable visual system across employer-brand touchpoints.",
      "Used colleague feedback and UX data to restructure the global Talent Acquisition SharePoint hub, centralizing its asset library and workflows.",
      "Built a global toolkit containing 640+ templates, 32 banners, thousands of photos, and customizable LinkedIn assets.",
    ],
    visual: "loblaw",
    coverEyebrow: "Employer brand · UX",
    coverTitle: "Talent experiences",
    coverMetric: "23 standardized banners",
    coverImage: "/projects/work/loblaw/loblaw-companies-limited-logo.png",
    coverImageAlt: "Loblaw Companies Limited",
    coverImageStyle: "loblaw-logo",
    aspect: "1.25 / 1",
    subprojects: loblawSubprojects,
  },
  {
    slug: "aves-lair-community",
    title: "Aves Lair",
    description: "Community engagement and content strategy for a 600+ member founder and investor network, informed by channel-performance analysis.",
    organization: "Syntax Capital",
    role: "Community Engagement Intern",
    period: "June 2021 – July 2022",
    impact: [
      "Managed and engaged a 600+ member Slack community while coordinating events with employees, investors, founders, and other stakeholders.",
      "Analyzed website, X, and YouTube performance to connect traffic and engagement changes with social campaigns and inform channel strategy.",
    ],
    mediaSections: [
      {
        eyebrow: "Video production · Event marketing",
        title: "Winter 2021 Demo Day Trailer",
        description: "Working with Aves Lair's marketing team, I helped shape and create this promotional trailer for Winter 2021 Demo Day, building anticipation for an event where participating companies presented their work. Edited in Final Cut Pro.",
        layout: "wide",
        items: [
          {
            type: "youtube",
            videoId: "rpm9zrm5yqk",
            href: "https://www.youtube.com/watch?v=rpm9zrm5yqk",
            caption: "Watch the Demo Day trailer on YouTube",
            aspect: "16 / 9",
          },
        ],
      },
    ],
    visual: "aves",
    coverEyebrow: "Community · Content strategy",
    coverTitle: "Aves Lair",
    coverMetric: "600+ community members",
    coverImage: "/projects/work/aves-lair/aves-lair-logo-purple.png",
    coverImageAlt: "Aves Lair",
    coverImageStyle: "aves-logo",
    aspect: "1.25 / 1",
  },
  {
    slug: "chennyvisuals",
    title: "chennyvisuals",
    description: "Photography, video, and graphic-design work across 38 client assets, including coverage for the ICFF Lavazza IncluCity Festival.",
    organization: "Self-employed",
    role: "Content Producer & Creative Marketer",
    period: "August 2020 – Present",
    impact: [
      "Selected as lead opening-night and assistant celebrity photographer for the 2024–2025 ICFF Lavazza IncluCity Festival, covering Isabella Rossellini and Giancarlo Esposito.",
      "Led client projects from discovery and creative direction through production, editing, and revision, delivering 38 video, photography, and graphic-design assets across multiple industries.",
    ],
    visual: "chenny",
    coverEyebrow: "Photo · Video · Design",
    coverTitle: "chennyvisuals",
    coverMetric: "38 client deliverables",
    aspect: "1.85 / 1",
  },
];

// Each slot has a CSS mock object for now. Add image, video, poster, and href
// fields to replace the mock object with real personal work later.
export const playgroundItems = [
  {
    id: "soccer",
    slot: "soccer",
    label: "My favorite sport - soccer!",
    kind: "sport",
    image: "/projects/playground/stickers/soccer-sticker.png",
    alt: "Illustrated Premier League soccer ball sticker",
    rotation: "-4deg",
    scale: 1,
  },
  {
    id: "photography",
    slot: "one",
    label: "My Art",
    kind: "photo",
    image: "/projects/playground/stickers/a7riii-sticker.png",
    alt: "Sony A7R III camera sticker",
    href: "#playground/photography",
    rotation: "-3deg",
    scale: 1.08,
  },
  {
    id: "personality",
    slot: "middle",
    label: "ENFJ",
    kind: "personality",
    image: "/projects/playground/stickers/enfj-sticker.png",
    alt: "ENFJ personality character sticker",
    href: "#about",
    rotation: "-1deg",
    scale: 1,
  },
  {
    id: "projects",
    slot: "seven",
    label: "My Design",
    kind: "projects",
    image: "/projects/playground/stickers/macbook-sticker.png",
    alt: "MacBook sticker",
    href: "#playground/design",
    rotation: "2deg",
    scale: 1.02,
  },
];

export const about = {
  eyebrow: "about",
  paragraphs: [
    "I'm a digital designer and content strategist passionate about creating thoughtful, user-centered experiences.",
    "With a background in Digital Enterprise Management from the University of Toronto, I bring together UX/UI design, digital strategy, content, and visual storytelling.",
    "I'm especially interested in the intersection of art, design, technology, and business, and how they can come together to create experiences that are meaningful, engaging, and impactful.",
  ],
  callout: "Let's make something meaningful.",
  availability: "Available for digital design, content strategy, and creative projects.",
};
